# Example configuration 

# Possible locations:
# $HOME/.config/mist/mist.toml
# $HOME/.config/mist.toml
# $HOME/.mist.toml

# The name of the synchronization profile
[sync] 

# The directory to sync
directory = "/home/user/sync"

# The ssh address to connect to
ssh_address = "user@host"

# The gpg key id to encrypt the files with
gpg_id = "user@email.com"

temp_folder = "/tmp/sync"

# Optionally, specify the gpg command to use 
# gpg_program = "/bin/qubes-gpg-client-wrapper" # if Qubes OS 
gpg_program = "/bin/gpg"
